"""initial pipeline metadata

Revision ID: 2af5c697ace9
Revises:
Create Date: 2026-09-19 21:55:46.987071
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import Text

revision: str = "2af5c697ace9"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pipeline_runs",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("graph_schema", sa.String(length=64), nullable=False),
        sa.Column("graph_version", sa.String(length=128), nullable=False),
        sa.Column("code_revision", sa.String(length=128), nullable=False),
        sa.Column("container_digest", sa.String(length=256), nullable=True),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_artifact_id", sa.String(length=128), nullable=False),
        sa.Column(
            "configuration",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "budget",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_by", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("next_event_sequence", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pipeline_events",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("sequence", sa.BigInteger(), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("subject_id", sa.String(length=128), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "sequence"),
    )
    op.create_index(
        "ix_pipeline_events_resume", "pipeline_events", ["run_id", "sequence"], unique=False
    )
    op.create_table(
        "pipeline_nodes",
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("node_id", sa.String(length=128), nullable=False),
        sa.Column(
            "stage_definition",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "dependencies",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("selected_attempt_id", sa.String(length=128), nullable=True),
        sa.Column("parent_node_id", sa.String(length=128), nullable=True),
        sa.Column("branch_key", sa.String(length=128), nullable=True),
        sa.Column("blocked_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("run_id", "node_id"),
        sa.UniqueConstraint("run_id", "node_id"),
    )
    op.create_table(
        "pipeline_attempts",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("node_id", sa.String(length=128), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("retry_of", sa.String(length=128), nullable=True),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=True),
        sa.Column(
            "parameters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "command",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("code_revision", sa.String(length=128), nullable=False),
        sa.Column("environment_fingerprint", sa.String(length=64), nullable=False),
        sa.Column(
            "input_artifact_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "output_artifact_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("provider_operation_id", sa.String(length=256), nullable=True),
        sa.Column(
            "costs",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["retry_of"],
            ["pipeline_attempts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id", "node_id"],
            ["pipeline_nodes.run_id", "pipeline_nodes.node_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "node_id", "number"),
    )
    op.create_index("ix_pipeline_attempts_status", "pipeline_attempts", ["status"], unique=False)
    op.create_table(
        "pipeline_approvals",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("node_id", sa.String(length=128), nullable=False),
        sa.Column("attempt_id", sa.String(length=128), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("requested_by", sa.String(length=256), nullable=False),
        sa.Column("decided_by", sa.String(length=256), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["pipeline_attempts.id"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "node_id", "attempt_id", "kind"),
    )
    op.create_index(
        "ix_pipeline_approvals_pending", "pipeline_approvals", ["run_id", "decision"], unique=False
    )
    op.create_table(
        "pipeline_artifacts",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=128), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size", sa.BigInteger(), nullable=False),
        sa.Column("media_type", sa.String(length=256), nullable=False),
        sa.Column("storage_key", sa.Text(), nullable=False),
        sa.Column("producer_attempt_id", sa.String(length=128), nullable=True),
        sa.Column("contract", sa.String(length=128), nullable=True),
        sa.Column("preview_artifact_id", sa.String(length=128), nullable=True),
        sa.Column(
            "artifact_metadata",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["preview_artifact_id"],
            ["pipeline_artifacts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["producer_attempt_id"],
            ["pipeline_attempts.id"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "role", "sha256", "producer_attempt_id"),
    )
    op.create_index("ix_pipeline_artifacts_sha256", "pipeline_artifacts", ["sha256"], unique=False)
    op.create_table(
        "pipeline_operator_messages",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("node_id", sa.String(length=128), nullable=True),
        sa.Column("attempt_id", sa.String(length=128), nullable=True),
        sa.Column("author", sa.String(length=256), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column(
            "attachment_artifact_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["pipeline_attempts.id"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_pipeline_messages_scope",
        "pipeline_operator_messages",
        ["run_id", "node_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "pipeline_provider_claims",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("attempt_id", sa.String(length=128), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("idempotency_key", sa.String(length=256), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("logical_stage", sa.String(length=128), nullable=False),
        sa.Column("operation", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("parameters_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("provider_operation_id", sa.String(length=256), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("estimated_cost", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["pipeline_attempts.id"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "idempotency_key"),
    )
    op.create_index(
        "ix_pipeline_claims_source_stage",
        "pipeline_provider_claims",
        ["source_sha256", "logical_stage"],
        unique=False,
    )
    op.create_table(
        "pipeline_quality_decisions",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("run_id", sa.String(length=128), nullable=False),
        sa.Column("node_id", sa.String(length=128), nullable=False),
        sa.Column("attempt_id", sa.String(length=128), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column(
            "evidence",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "proposed_parameters",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("hypothesis", sa.Text(), nullable=True),
        sa.Column("decided_by", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["pipeline_attempts.id"],
        ),
        sa.ForeignKeyConstraint(["run_id"], ["pipeline_runs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("pipeline_quality_decisions")
    op.drop_index("ix_pipeline_claims_source_stage", table_name="pipeline_provider_claims")
    op.drop_table("pipeline_provider_claims")
    op.drop_index("ix_pipeline_messages_scope", table_name="pipeline_operator_messages")
    op.drop_table("pipeline_operator_messages")
    op.drop_index("ix_pipeline_artifacts_sha256", table_name="pipeline_artifacts")
    op.drop_table("pipeline_artifacts")
    op.drop_index("ix_pipeline_approvals_pending", table_name="pipeline_approvals")
    op.drop_table("pipeline_approvals")
    op.drop_index("ix_pipeline_attempts_status", table_name="pipeline_attempts")
    op.drop_table("pipeline_attempts")
    op.drop_table("pipeline_nodes")
    op.drop_index("ix_pipeline_events_resume", table_name="pipeline_events")
    op.drop_table("pipeline_events")
    op.drop_table("pipeline_runs")
    # ### end Alembic commands ###
